### ISSUE TITLE
[2pts] Setup kanban

### ISSUE THREAD

**Issue by TamaraDimov** [TamaraDimov/vespa-rentals-backend#21]
[Kanban board for this project](https://github.com/users/TamaraDimov/projects/4)

Team Members:
 - @TamaraDimov 
 - @kifle23
 - @danielsafari143 
 - @Besufekad-HAZ 

![image](https://github.com/TamaraDimov/vespa-rentals-backend/assets/23375153/f1f83ca7-618c-423d-b5db-f435d0c29f2f)

**Comment by Meltrust** [comment]
Hi @Besufekad-HAZ

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @Besufekad-HAZ,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

- All cards have been assigned



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️

- [ ] According to the project requirements:

![image](https://github.com/Salimer/Final-Capstone-Back-End/assets/57421823/cdc17b5a-c770-49c6-81cb-7d02808c4ede)

This card does not have any points:

![image](https://github.com/TamaraDimov/vespa-rentals-backend/assets/57421823/2f8575c7-189e-4c7c-bf43-694394db737f)

Kindly add some points to this card, in order to meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

**Comment by Meltrust** [comment]
Hi @Besufekad-HAZ,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete! 

### To highlight

- All cards now have pointings✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
